<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>SWSimTool.Infrastructure</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SWSimTool.Core/SWSimTool.Core.csproj">
      <Name>SWSimTool.Core</Name>
    </ProjectReference>
    <ProjectReference Include="../SWSimTool.Application/SWSimTool.Application.csproj">
      <Name>SWSimTool.Application</Name>
    </ProjectReference>
  </ItemGroup>
</Project>
