<Project>
  <Import Project="$(MSBuildThisFileDirectory)Version.props" />
  <PropertyGroup>
    <RepositoryRoot>$(MSBuildThisFileDirectory)</RepositoryRoot>
    <Configuration Condition="'$(Configuration)' == ''">Release</Configuration>
    <BaseOutputPath>$(RepositoryRoot)build/bin/$(MSBuildProjectName)/</BaseOutputPath>
    <BaseIntermediateOutputPath>$(RepositoryRoot)build/obj/$(MSBuildProjectName)/</BaseIntermediateOutputPath>
    <OutputPath>$(BaseOutputPath)$(Configuration)/</OutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)$(Configuration)/</IntermediateOutputPath>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <PathMap>$(RepositoryRoot)=/_/</PathMap>
    <Version>$(SWSimToolVersion)</Version>
    <AssemblyVersion>$(SWSimToolVersion).0</AssemblyVersion>
    <FileVersion>$(SWSimToolVersion).0</FileVersion>
    <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Product>SWSimTool</Product>
    <DebugType>portable</DebugType>
    <Nullable>disable</Nullable>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
  </PropertyGroup>
</Project>
