<Project>
  <PropertyGroup>
    <OutputPath>$(BaseOutputPath)$(Configuration)\$(BuildFramework)\</OutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)$(Configuration)\$(BuildFramework)\</IntermediateOutputPath>
    <PreBuildEvent />
  </PropertyGroup>
  <Target Name="GenerateCommitVersion" BeforeTargets="PrepareForBuild" Condition="'$(MSBuildProjectName)' == 'SWSimTool'">
    <Exec Command="powershell.exe -NoProfile -ExecutionPolicy Bypass -File &quot;$(RepositoryRoot)tools\build\UpdateVersionInfo.ps1&quot; -filename &quot;$(IntermediateOutputPath)VersionInfo.cs&quot;" />
  </Target>
</Project>
