<Project>
  <PropertyGroup>
    <PreBuildEvent />
  </PropertyGroup>
  <Target Name="GenerateCommitVersion" BeforeTargets="GenerateAssemblyInfo" Condition="'$(TargetFramework)' != ''">
    <Exec Command="powershell.exe -NoProfile -ExecutionPolicy Bypass -File &quot;$(RepositoryRoot)tools/build/UpdateVersionInfo.ps1&quot; -filename &quot;$(IntermediateOutputPath)VersionInfo.cs&quot; -Version &quot;$(SWSimToolVersion)&quot;" />
    <ItemGroup><Compile Include="$(IntermediateOutputPath)VersionInfo.cs" /></ItemGroup>
  </Target>
</Project>
