<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>CoreTests</AssemblyName>
    <OutputType>Exe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <StartupObject>CoreTestRunner</StartupObject>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="SolidWorks.Interop.sldworks">
      <HintPath>$(SolidWorksDir)/SolidWorks.Interop.sldworks.dll</HintPath>
    </Reference>
    <Reference Include="SolidWorks.Interop.swconst">
      <HintPath>$(SolidWorksDir)/SolidWorks.Interop.swconst.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/SWSimTool.Core/SWSimTool.Core.csproj">
      <Name>SWSimTool.Core</Name>
    </ProjectReference>
    <ProjectReference Include="../../src/SWSimTool.Application/SWSimTool.Application.csproj">
      <Name>SWSimTool.Application</Name>
    </ProjectReference>
    <ProjectReference Include="../../src/SWSimTool.Infrastructure/SWSimTool.Infrastructure.csproj">
      <Name>SWSimTool.Infrastructure</Name>
    </ProjectReference>
    <ProjectReference Include="../../src/SWSimTool.SolidWorks/SWSimTool.SolidWorks.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MathNet.Numerics.Signed" Version="4.7.0" />
  </ItemGroup>
</Project>
