<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0</TargetFrameworks>
    <AssemblyName>SWSimTool.Application</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" Condition="'$(TargetFramework)' == 'net48'" />
    <Reference Include="System.Core" Condition="'$(TargetFramework)' == 'net48'" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SWSimTool.Core/SWSimTool.Core.csproj">
      <Name>SWSimTool.Core</Name>
    </ProjectReference>
  </ItemGroup>
</Project>
