<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>SWSimTool.Application</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SWSimTool.Core/SWSimTool.Core.csproj">
      <Name>SWSimTool.Core</Name>
    </ProjectReference>
  </ItemGroup>
</Project>
