<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>SWSimTool</AssemblyName>
    <OutputType>Library</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <RootNamespace>SWSimTool</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <RegisterForComInterop>false</RegisterForComInterop>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
    <SolidWorksDir Condition="'$(SolidWorksDir)' == ''">C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS</SolidWorksDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="SolidWorks.Interop.sldworks">
      <HintPath>$(SolidWorksDir)\SolidWorks.Interop.sldworks.dll</HintPath>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </Reference>
    <Reference Include="SolidWorks.Interop.swconst">
      <HintPath>$(SolidWorksDir)\SolidWorks.Interop.swconst.dll</HintPath>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </Reference>
    <Reference Include="SolidWorks.Interop.swpublished">
      <HintPath>$(SolidWorksDir)\SolidWorks.Interop.swpublished.dll</HintPath>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </Reference>
    <Reference Include="solidworkstools, Version=2.0.0.0, Culture=neutral, PublicKeyToken=bd18593873b4686d, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(SolidWorksDir)\solidworkstools.dll</HintPath>
    </Reference>
    <Reference Include="System">
      <Name>System</Name>
    </Reference>
    <Reference Include="System.ComponentModel.Composition" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Data">
      <Name>System.Data</Name>
    </Reference>
    <Reference Include="System.DirectoryServices" />
    <Reference Include="System.Drawing">
      <Name>System.Drawing</Name>
    </Reference>
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Numerics" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Web" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xaml" />
    <Reference Include="System.XML">
      <Name>System.XML</Name>
    </Reference>
    <Reference Include="System.Xml.Linq" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="GlobalSuppressions.cs" />
    <Compile Include="RobotModel\SolidWorksRobotModelBuilder.cs" />
    <Compile Include="Simulation\AttachmentService.cs" />
    <Compile Include="Simulation\SimulationStorage.cs" />
    <Compile Include="Simulation\StableReferences.cs" />
    <Compile Include="Utilities\PerformanceScope.cs" />
    <Compile Include="Simulation\ProjectExport.cs" />
    <Compile Include="Simulation\NativeSimulationGeometry.cs" />
    <Compile Include="Simulation\CadRobotCoreBuilder.cs" />
    <Compile Include="Simulation\ProjectSourceBuilder.cs" />
    <Compile Include="URDFExport\ExportHelperNativeSource.cs" />
    <Compile Include="Simulation\SimulationSession.cs" />
    <Compile Include="Simulation\ConfigurationSession.cs" />
    <Compile Include="Simulation\ConfigurationEditingContext.cs" />
    <Compile Include="Simulation\ConfigurationRebuild.cs" />
    <Compile Include="Simulation\CadReferenceSnapshot.cs" />
    <Compile Include="Simulation\ProjectSourceCache.cs" />
    <Compile Include="UI\SimulationEditorControl.cs" />
    <Compile Include="UI\SolverParametersControl.cs" />
    <Compile Include="UI\JointEditorControl.cs" />
    <Compile Include="UI\JointPropertyManager.cs" />
    <Compile Include="Simulation\JointConfiguration.cs" />
    <Compile Include="Simulation\JointReferenceService.cs" />
    <Compile Include="UI\SimulationPropertyManager.cs" />
    <Compile Include="Simulation\CollisionGeometryService.cs" />
    <Compile Include="Simulation\CollisionPreview.cs" />
    <Compile Include="UI\CollisionEditorControl.cs" />
    <Compile Include="UI\CollisionPropertyManager.cs" />
    <Compile Include="UI\MeshExportSettingsForm.cs" />
    <Compile Include="UI\MuJoCoToolsForm.cs" />
    <Compile Include="UI\SimulationConfigForm.cs" />
    <Compile Include="UI\IMessageBox.cs" />
    <Compile Include="UI\MessageBoxHelper.cs" />
    <Compile Include="URDF\Mimic.cs" />
    <Compile Include="Utilities\Logger.cs" />
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="ROS\ROSFiles.cs" />
    <Compile Include="UI\TreeMergedEventArgs.cs" />
    <Compile Include="UI\TreeMergeWPF.xaml.cs">
      <DependentUpon>TreeMergeWPF.xaml</DependentUpon>
    </Compile>
    <Compile Include="UI\TreeModifiedEventArgs.cs" />
    <Compile Include="UI\URDFTreeView.cs" />
    <Compile Include="UI\AssemblyExportForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="UI\AssemblyExportForm.Designer.cs">
      <DependentUpon>AssemblyExportForm.cs</DependentUpon>
    </Compile>
    <Compile Include="AssemblyInfo.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="URDFExport\CSV\ContextToColumns.cs" />
    <Compile Include="URDFExport\CSV\CSVImportExport.cs" />
    <Compile Include="URDFExport\ConfigurationSerialization.cs" />
    <Compile Include="URDFExport\ExportHelper.cs" />
    <Compile Include="URDFExport\ExportHelperExtension.cs" />
    <Compile Include="UI\AssemblyExportFormExtension.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="URDFExport\CommonSwOperations.cs" />
    <Compile Include="URDFExport\ExportPropertyManagerExtension.cs" />
    <Compile Include="Utilities\MathOPS.cs" />
    <Compile Include="SW\EventHandling.cs" />
    <Compile Include="UI\PartExportForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="UI\PartExportForm.Designer.cs">
      <DependentUpon>PartExportForm.cs</DependentUpon>
    </Compile>
    <Compile Include="SW\SwAddin.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="URDFExport\URDFMerge\TreeMerger.cs" />
    <Compile Include="URDFExport\URDFMerge\URDFTreeCorrespondance.cs" />
    <Compile Include="URDF\Axis.cs" />
    <Compile Include="URDF\Calibration.cs" />
    <Compile Include="URDF\ChildLink.cs" />
    <Compile Include="URDF\Collision.cs" />
    <Compile Include="URDF\Color.cs" />
    <Compile Include="URDF\Dynamics.cs" />
    <Compile Include="URDF\Geometry.cs" />
    <Compile Include="URDF\Inertia.cs" />
    <Compile Include="URDF\Inertial.cs" />
    <Compile Include="URDF\Joint.cs" />
    <Compile Include="URDF\Limit.cs" />
    <Compile Include="URDF\Link.cs" />
    <Compile Include="URDF\LinkNode.cs" />
    <Compile Include="URDF\Mass.cs" />
    <Compile Include="URDF\Material.cs" />
    <Compile Include="URDF\Mesh.cs" />
    <Compile Include="URDF\Origin.cs" />
    <Compile Include="URDF\PackageXMLWriter.cs" />
    <Compile Include="URDF\ParentLink.cs" />
    <Compile Include="URDF\Robot.cs" />
    <Compile Include="URDF\SafetyController.cs" />
    <Compile Include="URDF\Texture.cs" />
    <Compile Include="URDF\URDFAttribute.cs" />
    <Compile Include="URDFExport\ExportPropertyManager.cs" />
    <Compile Include="URDFExport\URDFPackage.cs" />
    <Compile Include="URDF\URDFElement.cs" />
    <Compile Include="URDF\URDFWriter.cs" />
    <Compile Include="URDF\Visual.cs" />
    <Compile Include="Versioning\Version.cs" />
    <Compile Include="Simulation\SolidWorksCadSource.cs" />
    <Compile Include="Simulation\SolidWorksAttributeDocumentStore.cs" />
    <Compile Include="UI\ReferencePreviewDialog.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Include="UI\AssemblyExportForm.resx">
      <DependentUpon>AssemblyExportForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="UI\PartExportForm.resx">
      <DependentUpon>PartExportForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="UI\Resources\Images\ToolbarLarge.bmp" />
    <EmbeddedResource Include="UI\Resources\Images\ToolbarSmall.bmp" />
    <EmbeddedResource Include="UI\Resources\Images\MainIconLarge.bmp" />
    <EmbeddedResource Include="UI\Resources\Images\MainIconSmall.bmp" />
    <EmbeddedResource Include="UI\Resources\Images\AddinIcon.bmp" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Properties\DataSources\SwAddin.datasource">
      <SubType>Designer</SubType>
    </None>
    <None Include="SWSimTool.ruleset" />
  </ItemGroup>
  <ItemGroup>
    <Page Include="UI\TreeMergeWPF.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UI\UIResources.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Content Include="images\ros_logo_128x128.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\ros_logo_16x16.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\ros_logo_20x20.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\ros_logo_32x32.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\ros_logo_40x40.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\ros_logo_64x64.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\ros_logo_96x96.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="SWSimTool.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\runtime\python\native_support.py">
      <Link>mujoco_backend\native_support.py</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\runtime\python\simplify_stl.py">
      <Link>mujoco_backend\simplify_stl.py</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\runtime\python\mesh_cache.py">
      <Link>mujoco_backend\mesh_cache.py</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\runtime\python\incremental.py">
      <Link>mujoco_backend\incremental.py</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\runtime\python\solver.py">
      <Link>mujoco_backend\solver.py</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\runtime\python\requirements.txt">
      <Link>mujoco_backend\requirements.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SWSimTool.Core\SWSimTool.Core.csproj">
      <Name>SWSimTool.Core</Name>
    </ProjectReference>
    <ProjectReference Include="..\SWSimTool.Application\SWSimTool.Application.csproj">
      <Name>SWSimTool.Application</Name>
    </ProjectReference>
    <ProjectReference Include="..\SWSimTool.Infrastructure\SWSimTool.Infrastructure.csproj">
      <Name>SWSimTool.Infrastructure</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="7.1.1" />
    <PackageReference Include="log4net" Version="2.0.8" />
    <PackageReference Include="MathNet.Numerics.Signed" Version="4.7.0" />
  </ItemGroup>
</Project>
