param([string]$Payload="bin/SWSimTool.SolidWorks/Release/net48")
$ErrorActionPreference='Stop'
$root=$(for ($p=$PSScriptRoot; $p; $p=Split-Path -Parent $p) { if (Test-Path -LiteralPath (Join-Path $p 'SWSimTool.sln')) { $p; break } })
$testConfiguration=if($env:SWSIMTOOL_TEST_CONFIGURATION){$env:SWSIMTOOL_TEST_CONFIGURATION}else{'Release'}
$folder=Join-Path $root ('build\stable-reference-audit-'+[Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $folder | Out-Null
$bin=Join-Path $root ('build\'+$Payload)
$interop=if($env:SOLIDWORKS_DIR){$env:SOLIDWORKS_DIR}else{'D:\sw\sw2025\SOLIDWORKS'}
$refs=@("$bin\SWSimTool.dll","$bin\SWSimTool.Core.dll","$bin\SWSimTool.Application.dll","$bin\SWSimTool.Infrastructure.dll","$bin\MathNet.Numerics.dll","$(Join-Path $root "build/bin/SWSimTool.Tests/$testConfiguration/net48/Moq.dll")","$(Join-Path $root "build/bin/SWSimTool.Tests/$testConfiguration/net48/Castle.Core.dll")","$interop\SolidWorks.Interop.sldworks.dll",'System.Core','System.Xml','System.Xml.Linq','System.Web.Extensions','System.Runtime.Serialization','System.Windows.Forms')
@("build/bin/SWSimTool.Tests/$testConfiguration/net48/System.Threading.Tasks.Extensions.dll","build/bin/SWSimTool.Tests/$testConfiguration/net48/System.Runtime.CompilerServices.Unsafe.dll") | ForEach-Object { [Reflection.Assembly]::LoadFrom((Join-Path $root $_)) | Out-Null }
$refs | Where-Object {$_ -like '*.dll'} | ForEach-Object {[Reflection.Assembly]::LoadFrom($_)|Out-Null}
[SWSimTool.Utilities.Logger].GetField('Initialized',[Reflection.BindingFlags]'NonPublic,Static').SetValue($null,$true)
Add-Type -ReferencedAssemblies $refs -TypeDefinition @'
using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;
using System.Runtime.Serialization;using Moq;using SolidWorks.Interop.sldworks;using SWSimTool.URDF;using SWSimTool.URDFExport;using SWSimTool.Simulation;using SWSimTool.RobotModel;
public static class StableReferenceAudit {
 static int checks;static void Check(bool ok,string text){if(!ok)throw new Exception(text);checks++;Console.WriteLine("PASS: "+text);}
 sealed class Fixture {
  public LinkNode tree;public LinkNode a,b;public string directory;public Mock<ModelDoc2> model;
  public Fixture(string directory){this.directory=directory;Directory.CreateDirectory(directory);var root=new Link(null);root.Name="base";tree=new LinkNode(root);foreach(string name in new[]{"a","b"}){var link=new Link(root);link.Name=name;link.Joint.Name="j_"+name;link.Joint.Type="continuous";link.Joint.Axis.SetXYZ(new[]{0.0,0,1});var node=new LinkNode(link);tree.Nodes.Add(node);if(name=="a")a=node;else b=node;}tree.UpdateLinkTree(null);
   var configuration=new Mock<Configuration>();configuration.SetupGet(x=>x.Name).Returns("test");var manager=new Mock<ConfigurationManager>();manager.SetupGet(x=>x.ActiveConfiguration).Returns(configuration.Object);model=new Mock<ModelDoc2>();model.SetupGet(x=>x.ConfigurationManager).Returns(manager.Object);var emptyFeatures=new Mock<FeatureManager>();emptyFeatures.Setup(x=>x.GetFeatures(true)).Returns(new object[0]);model.SetupGet(x=>x.FeatureManager).Returns(emptyFeatures.Object);
  }
  public RobotCoreSnapshot Core(){var root=tree.UpdateLinkTree(null);Action<Link> mass=null;mass=l=>{l.Inertial.Mass.Value=1;l.Inertial.Inertia.Ixx=.1;l.Inertial.Inertia.Iyy=.1;l.Inertial.Inertia.Izz=.1;foreach(var c in l.Children)mass(c);};mass(root);var robot=new Robot();robot.SetBaseLink(root);return SolidWorksRobotModelBuilder.FromResolvedRobot(robot,new Dictionary<string,MeshSource>());}
  public string Source(){return ExportFingerprint.Hash(ConfigurationSerialization.WriteTree(tree));}
  public SimulationProject Reopen(SimulationProject p,string stage){var d=new SimulationStorage.Document();d.configurations["test"]=new SimulationStorage.Entry{urdf_xml=ConfigurationSerialization.WriteTree(tree),simulation=p};string path=Path.Combine(directory,stage+".json");File.WriteAllText(path,ExportFingerprint.Serializer().Serialize(d));var e=SimulationStorage.Parse(File.ReadAllText(path)).configurations["test"];tree=ConfigurationSerialization.ReadTree(e.urdf_xml,e.urdf_version);a=tree.Nodes.Cast<LinkNode>().FirstOrDefault(n=>n.Name=="a"||n.Name=="renamed_a");b=tree.Nodes.Cast<LinkNode>().Single(n=>n.Name=="b");StableReferences.Normalize(e.simulation,tree);return e.simulation;}
 }
 sealed class Case {public string name,kind,key;public Func<SimulationProject,object> item;public Func<Fixture,SimulationProject> create;}
 static void LegacyReadCache(string folder){
  var f=new Fixture(Path.Combine(folder,"legacy_reads"));var p=Project();Sites(f,p);p.actuators.Add(new ActuatorConfig{name="motor",joint="j_a"});
  var xml=System.Xml.Linq.XElement.Parse(ConfigurationSerialization.WriteTree(f.tree));foreach(var node in xml.Descendants().Where(x=>x.Name.LocalName=="stableId").ToArray())node.Remove();
  var document=new SimulationStorage.Document();document.configurations["test"]=new SimulationStorage.Entry{urdf_xml=xml.ToString(),simulation=p};
  string raw=ExportFingerprint.Serializer().Serialize(document),original=raw;
  Func<Mock<ModelDoc2>> model=()=>{
   var config=new Mock<Configuration>();config.SetupGet(x=>x.Name).Returns("test");
   var manager=new Mock<ConfigurationManager>();manager.SetupGet(x=>x.ActiveConfiguration).Returns(config.Object);
   var parameter=new Mock<Parameter>();parameter.Setup(x=>x.GetStringValue()).Returns(()=>raw);
   var attribute=new Mock<SolidWorks.Interop.sldworks.Attribute>();attribute.Setup(x=>x.GetName()).Returns(SimulationStorage.NodeName);attribute.Setup(x=>x.GetParameter("data")).Returns(parameter.Object);
   var feature=new Mock<Feature>();feature.Setup(x=>x.GetTypeName2()).Returns("Attribute");feature.Setup(x=>x.GetSpecificFeature2()).Returns(attribute.Object);
   var features=new Mock<FeatureManager>();features.Setup(x=>x.GetFeatures(true)).Returns(new object[]{feature.Object});
   var m=new Mock<ModelDoc2>();var nodeExtension=new Mock<ModelDocExtension>();nodeExtension.Setup(x=>x.GetPersistReference3(It.IsAny<object>())).Returns(new byte[]{9,8,7});m.SetupGet(x=>x.Extension).Returns(nodeExtension.Object);m.SetupGet(x=>x.FeatureManager).Returns(features.Object);m.SetupGet(x=>x.ConfigurationManager).Returns(manager.Object);m.Setup(x=>x.GetConfigurationNames()).Returns(new[]{"test"});m.Setup(x=>x.GetConfigurationByName("test")).Returns(config.Object);return m;
  };
  var mock=model();var loaded=SimulationStorage.Load(mock.Object);var entry=SimulationStorage.LoadEntry(mock.Object);var tree=ConfigurationSerialization.ReadTree(entry.urdf_xml,1.4);var a=(LinkNode)tree.Nodes[0];
  Check(loaded.attachments[0].link_id==a.Link.StableId,"Name-only site parent matches independently loaded export tree");
  Check(loaded.actuators[0].joint_id==a.Link.Joint.StableId,"Name-only actuator matches independently loaded export joint");
  f.tree=tree;var core=f.Core();var snapshot=SimulationConfigBuilder.Build(loaded,core,Geometry(loaded,core));new RobotModel(core,snapshot);
  Check(true,"Independent legacy load/export path builds a valid RobotModel");
  int parses=SimulationStorage.ParseCount;var again=SimulationStorage.Load(mock.Object);
  Check(again.attachments[0].link_id==loaded.attachments[0].link_id&&SimulationStorage.ParseCount==parses,"Warm envelope cache retains migrated identities without reparse");
  loaded.attachments[0].name="unsaved_edit";Check(SimulationStorage.Load(mock.Object).attachments[0].name=="sa","Cached migration does not share mutable editor drafts");
  mock.Verify(x=>x.SetSaveFlag(),Times.Never());Check(raw==original,"Loading legacy data performs no CAD write or dirty flag");
  document.configurations["test"]=entry;raw=ExportFingerprint.Serializer().Serialize(document);var reopened=SimulationStorage.Load(model().Object);
  Check(reopened.attachments[0].link_id==a.Link.StableId&&reopened.actuators[0].joint_id==a.Link.Joint.StableId,"Serialized migration survives cold document reopen");
  Check(SimulationStorage.Load(mock.Object).attachments[0].link_id==a.Link.StableId,"External storage update invalidates cache while retaining saved IDs");
 }
 static SimulationProject Project(){return new SimulationProject{collision=new CollisionConfiguration()};}
 static void Sites(Fixture f,SimulationProject p){p.attachments.Add(new Attachment{name="sa",link="a",type="frame"});p.attachments.Add(new Attachment{name="sb",link="b",type="frame"});}
 static string Read(object item,string key){return (string)item.GetType().GetProperty(key).GetValue(item);}
 static void Set(object item,string key,string value){item.GetType().GetProperty(key).SetValue(item,value);}
 static List<Case> Cases(){var result=new List<Case>();
  result.Add(new Case{name="attachment.link",kind="link",key="link",create=f=>{var p=Project();p.attachments.Add(new Attachment{name="sa",link="a",type="frame"});return p;},item=p=>p.attachments[0]});
  result.Add(new Case{name="collision_geometry.link",kind="link",key="link",create=f=>{var p=Project();p.collision.geometries.Add(new CollisionGeometry{name="proxy",link="a"});return p;},item=p=>p.collision.geometries[0]});
  foreach(bool first in new[]{true,false}){bool x=first;result.Add(new Case{name="contact_pair."+(x?"link1":"link2"),kind="link",key=x?"link1":"link2",create=f=>{var p=Project();p.collision.allowed_pairs.Add(new CollisionPair{link1=x?"a":"b",link2=x?"b":"a"});return p;},item=p=>p.collision.allowed_pairs[0]});}
  result.Add(new Case{name="joint_settings.joint",kind="joint",key="joint",create=f=>{var p=Project();p.joints.Add(new JointConfiguration{joint="j_a",damping=.01});return p;},item=p=>p.joints[0]});
  result.Add(new Case{name="joint_force_limit.joint",kind="joint",key="joint",create=f=>{var p=Project();p.joint_force_limits.Add(new JointForceLimit{joint="j_a",lower=-1,upper=1});return p;},item=p=>p.joint_force_limits[0]});
  result.Add(new Case{name="actuator.joint",kind="joint",key="joint",create=f=>{var p=Project();p.actuators.Add(new ActuatorConfig{name="motor",joint="j_a"});return p;},item=p=>p.actuators[0]});
  result.Add(new Case{name="sensor.site",kind="site",key="site",create=f=>{var p=Project();Sites(f,p);p.sensors.Add(new SensorConfig{name="imu",site="sa"});return p;},item=p=>p.sensors[0]});
  foreach(string type in new[]{"connect","weld","joint"})foreach(string binding in type=="joint"?new[]{"joint"}:new[]{"site","body"})foreach(bool first in new[]{true,false}){
   string t=type,b=binding;bool x=first;string key=(b=="joint"?"joint":b=="body"?"body":"site")+(x?"1":"2");
   result.Add(new Case{name=t+"_"+b+"."+key,kind=b=="body"?"link":b=="joint"?"joint":"site",key=key,create=f=>{var p=Project();if(b=="site")Sites(f,p);p.equalities.Add(new EqualityConfig{name="eq",type=t,binding=b=="joint"?"site":b,site1=x?"sa":"sb",site2=x?"sb":"sa",joint1=x?"j_a":"j_b",joint2=x?"j_b":"j_a",body1=x?"a":"b",body2=x?"b":"a"});return p;},item=p=>p.equalities[0]});
  }
  foreach(string type in new[]{"pull","push","spring"})foreach(bool first in new[]{true,false}){string t=type;bool x=first;result.Add(new Case{name=t+"."+(x?"site1":"site2"),kind="site",key=x?"site1":"site2",create=f=>{var p=Project();Sites(f,p);p.site_forces.Add(new SiteForceConfig{name="force",type=t,site1=x?"sa":"sb",site2=x?"sb":"sa",magnitude=1,stiffness=1});return p;},item=p=>p.site_forces[0]});}
  return result;
 }
 static ResolvedSimulationGeometry Geometry(SimulationProject p,RobotCoreSnapshot core){
  var links=core.Links.ToDictionary(l=>l.Id,l=>l.Name);var sites=p.attachments.Select(a=>{if(!links.ContainsKey(a.link_id))throw new InvalidDataException("Unknown stable reference: "+a.link_id);return new SiteSnapshot(a.id,a.name,a.link_id,a.type=="frame",RigidTransform.Identity);}).ToArray();
  var proxies=p.collision.geometries.Select(g=>new CollisionGeometrySnapshot(g.id,g.name,g.link_id,g.link_id,g.type,g.size,g.xyz,g.rpy));return new ResolvedSimulationGeometry(sites,proxies);
 }
 static string Build(Fixture f,SimulationProject p,bool warm){
  string source=f.Source(),geometry=ProjectSourceCache.Geometry(p);var cached=warm?ProjectSourceCache.Find(f.model.Object,source,geometry):null;var core=cached==null?f.Core():cached.core;var resolved=Geometry(p,core);
  var snapshot=SimulationConfigBuilder.Build(p,core,resolved);var model=new RobotModel(core,snapshot);
  if(cached==null){string raw=Path.Combine(f.directory,"raw");Directory.CreateDirectory(raw);File.WriteAllText(Path.Combine(raw,"marker"),"owned");ProjectSourceCache.Store(f.model.Object,source,geometry,raw,null,p,null,new Dictionary<string,double[]>(),core,resolved,true);}
  return ExportFingerprint.Hash(new{core,simulation=model.Simulation});
 }
 static void Reject(Fixture f,SimulationProject p,bool warm,string id,string label){bool failed=false;try{Build(f,p,warm);}catch(InvalidDataException e){failed=e.Message.Contains(id);if(!failed)Console.WriteLine("UNEXPECTED: "+e.Message+" expected "+id);}Check(failed,label+" rejects the exact dangling ID");}
 static void ReplaceJoint(Fixture f,string name){var link=new Link(f.tree.Link);link.Name=f.a.Name;link.Joint.Name=name;link.Joint.Type="continuous";link.Joint.Axis.SetXYZ(new[]{0.0,0,1});f.tree.Nodes.Remove(f.a);f.a=new LinkNode(link);f.tree.Nodes.Add(f.a);}
 static void TypedCase(Case c,Fixture f,SimulationProject p){var core=f.Core();var geometry=Geometry(p,core);var snapshot=SimulationConfigBuilder.Build(p,core,geometry);object value=null;
 if(c.name.StartsWith("attachment"))value=snapshot.Sites[0];else if(c.name.StartsWith("collision_geometry"))value=snapshot.Collision.Geometries[0];else if(c.name.StartsWith("contact_pair"))value=snapshot.Collision.AllowedPairs[0];else if(c.name.StartsWith("joint_settings"))value=snapshot.Joints[0];else if(c.name.StartsWith("joint_force_limit"))value=snapshot.JointForceLimits[0];else if(c.name.StartsWith("actuator"))value=snapshot.Actuators[0];else if(c.name.StartsWith("sensor"))value=snapshot.Sensors[0];else if(c.name.StartsWith("connect_")||c.name.StartsWith("weld_")||c.name.StartsWith("joint_"))value=snapshot.Equalities[0];else value=snapshot.SiteForces[0];
 string field=char.ToUpperInvariant(c.key[0])+c.key.Substring(1)+"Id";var info=value.GetType().GetField(field);object previous=info.GetValue(value);info.SetValue(value,"deleted");bool rejected=false;try{new RobotModel(core,snapshot);}catch(InvalidDataException e){rejected=e.Message.Contains("deleted");}finally{info.SetValue(value,previous);}Check(rejected,c.name+" direct typed RobotModel rejects dangling ID before writing XML");
}
static void RunCase(Case c,string folder){
  var f=new Fixture(Path.Combine(folder,c.name));var p=c.create(f);StableReferences.Normalize(p,f.tree);string id=Read(c.item(p),c.key+"_id");Check(!string.IsNullOrWhiteSpace(id),c.name+" migrates to identity");
  p=f.Reopen(p,"created");Check(Read(c.item(p),c.key+"_id")==id,c.name+" save/reopen retains identity");
  string ownId=c.item(p).GetType().GetProperty("id")==null?null:Read(c.item(p),"id");
  if(c.kind=="link")f.a.Name=f.a.Link.Name="renamed_a";else if(c.kind=="joint")f.a.Link.Joint.Name="renamed_j_a";else p.RenameSite(p.attachments.Single(a=>a.name=="sa"),"renamed_sa");
  StableReferences.Normalize(p,f.tree);Check(Read(c.item(p),c.key+"_id")==id&&Read(c.item(p),c.key).StartsWith("renamed"),c.name+" rename follows original identity");
  p=f.Reopen(p,"renamed");Check(Read(c.item(p),c.key+"_id")==id&&(ownId==null||Read(c.item(p),"id")==ownId),c.name+" renamed save/reopen preserves own and target IDs");
  TypedCase(c,f,p);var initial=Build(f,p,true);var warm=Build(f,p,true);var cold=Build(f,p,false);Check(initial==warm&&warm==cold,c.name+" warm/cold model semantic fingerprints agree");
  if(c.kind=="link")f.tree.Nodes.Remove(f.a);else if(c.kind=="joint"){ReplaceJoint(f,"temporary");}else p.attachments.RemoveAll(a=>a.id==id);
  StableReferences.Normalize(p,f.tree);Check(Read(c.item(p),c.key+"_id")==id,c.name+" delete retains unresolved identity");Reject(f,p,true,id,c.name+" warm delete");
  if(c.kind=="link"){var l=new Link(f.tree.Link);l.Name="renamed_a";l.Joint.Name="replacement";l.Joint.Type="continuous";l.Joint.Axis.SetXYZ(new[]{0.0,0,1});f.tree.Nodes.Add(new LinkNode(l));}else if(c.kind=="joint")f.a.Link.Joint.Name="renamed_j_a";else p.attachments.Add(new Attachment{name="renamed_sa",link="a",type="frame"});
  StableReferences.Normalize(p,f.tree);p=f.Reopen(p,"recreated");Check(Read(c.item(p),c.key+"_id")==id,c.name+" same-name recreate/save/reopen never rebinds");Reject(f,p,true,id,c.name+" warm recreate");Reject(f,p,false,id,c.name+" cold recreate");
 }
 static void Mimic(string folder){var f=new Fixture(Path.Combine(folder,"mimic"));f.b.Link.Joint.Mimic.Update("j_a","2",".1");StableReferences.NormalizeTree(f.tree);string id=f.a.Link.Joint.StableId;Check(f.b.Link.Joint.Mimic.SourceJointId==id,"mimic resolves stable source identity");var p=f.Reopen(Project(),"created");f.a.Link.Joint.Name="renamed_j_a";StableReferences.NormalizeTree(f.tree);Check(f.b.Link.Joint.Mimic.JointName=="renamed_j_a"&&f.b.Link.Joint.Mimic.SourceJointId==id,"mimic rename preserves source");p=f.Reopen(p,"renamed");Check(f.b.Link.Joint.Mimic.SourceJointId==id&&f.b.Link.Clone().Joint.Mimic.SourceJointId==id,"mimic save/reopen/clone preserves ID");Check(Build(f,p,true)==Build(f,p,false),"mimic warm/cold agrees");ReplaceJoint(f,"renamed_j_a");p=f.Reopen(p,"recreated");Reject(f,p,true,id,"mimic warm recreate");Reject(f,p,false,id,"mimic cold recreate");}
 static void Legacy(string folder){var f=new Fixture(Path.Combine(folder,"legacy_unresolved"));var p=Project();p.actuators.Add(new ActuatorConfig{joint="missing"});p.sensors.Add(new SensorConfig{site="missing_site"});StableReferences.Normalize(p,f.tree);string j=p.actuators[0].joint_id,s=p.sensors[0].site_id;Check(!string.IsNullOrWhiteSpace(j)&&!string.IsNullOrWhiteSpace(s),"missing legacy names acquire persistent unresolved identities");f.a.Link.Joint.Name="missing";p.attachments.Add(new Attachment{name="missing_site",link="a",type="frame"});p=f.Reopen(p,"recreated");Check(p.actuators[0].joint_id==j&&p.sensors[0].site_id==s,"legacy unresolved identities never retry same-name migration");}
 static void Modes(string folder){var f=new Fixture(Path.Combine(folder,"collision_modes"));var p=Project();p.collision.link_modes["a"]="none";StableReferences.Normalize(p,f.tree);string id=f.a.Link.StableId;p=f.Reopen(p,"created");Check(p.collision.Mode(id)=="none","mode migration/save/reopen retains identity");f.a.Name=f.a.Link.Name="renamed_a";p=f.Reopen(p,"renamed");Check(p.collision.Mode(id)=="none","mode rename/save/reopen retains identity");Check(Build(f,p,true)==Build(f,p,false),"mode warm/cold agrees");f.tree.Nodes.Remove(f.a);StableReferences.Normalize(p,f.tree);Reject(f,p,true,id,"mode warm delete");var link=new Link(f.tree.Link);link.Name="renamed_a";link.Joint.Name="replacement";link.Joint.Type="continuous";link.Joint.Axis.SetXYZ(new[]{0.0,0,1});f.tree.Nodes.Add(new LinkNode(link));string replacementId=link.StableId;p=f.Reopen(p,"recreated");Check(p.collision.Mode(replacementId)=="mesh"&&p.collision.link_modes_by_id.ContainsKey(id),"mode same-name recreate/save/reopen never inherits");Reject(f,p,true,id,"mode warm recreate");Reject(f,p,false,id,"mode cold recreate");bool rejected=false;try{new RobotModel(f.Core(),new SimulationConfigSnapshot(Collision:new CollisionSnapshot(LinkModes:new Dictionary<string,string>{{"deleted","none"}})));}catch(InvalidDataException e){rejected=e.Message.Contains("deleted");}Check(rejected,"typed RobotModel rejects dangling mode ID");}
 static void Sidecar(Fixture f){var core=f.Core();var helper=(ExportHelper)FormatterServices.GetUninitializedObject(typeof(ExportHelper));helper.ActiveSWModel=f.model.Object;var service=new AttachmentService(helper,true);service.Project=Project();service.Project.attachments.Add(new Attachment{name="sa",link="a",link_id="deleted",type="frame"});var frames=core.Links.ToDictionary(x=>x.Name,x=>new[]{1.0,0,0,0,0,1.0,0,0,0,0,1.0,0,0,0,0,1.0});service.UseExportFrames(frames,core);
 foreach(string operation in new[]{"sidecar","preview","collision"}){bool rejected=false;try{if(operation=="sidecar")service.Export("robot.urdf");else if(operation=="preview")service.AttachmentPose(service.Project.attachments[0]);else service.ResolveCollision(new CollisionGeometry{name="proxy",link="a",link_id="deleted"});}catch(InvalidDataException e){rejected=e.Message.Contains("deleted");}Check(rejected,operation+" cannot resolve dangling link ID by matching display name");}}
 static void CadPid(Fixture f){var helper=(ExportHelper)FormatterServices.GetUninitializedObject(typeof(ExportHelper));helper.ActiveSWModel=f.model.Object;var extension=new Mock<ModelDocExtension>();int error=1;extension.Setup(x=>x.GetObjectByPersistReference3(It.IsAny<object>(),out error)).Returns((object)null);f.model.SetupGet(x=>x.Extension).Returns(extension.Object);var same=new Mock<Feature>();same.SetupProperty(x=>x.Name,"same");same.Setup(x=>x.GetTypeName2()).Returns("CoordSys");f.model.Setup(x=>x.FirstFeature()).Returns(same.Object);var service=new AttachmentService(helper,true);service.Project=Project();var core=f.Core();service.UseExportFrames(core.Links.ToDictionary(x=>x.Name,x=>new[]{1.0,0,0,0,0,1.0,0,0,0,0,1.0,0,0,0,0,1.0}),core);string missing=Convert.ToBase64String(new byte[]{1,2,3}),linkId=core.Links.Single(x=>x.Name=="a").Id;
 foreach(string operation in new[]{"source","component","point_or_frame","dimension_edge"}){bool rejected=false;try{if(operation=="source"||operation=="component")service.AttachmentPose(new Attachment{name="sa",link="a",link_id=linkId,type="frame",source_name="same",source_pid=missing,component_name="same",component_pid=operation=="component"?missing:null});else{var g=new CollisionGeometry{link="a",link_id=linkId,definition=operation=="point_or_frame"?"frame":"manual"};if(operation=="point_or_frame")g.references.Add(new CollisionReference{pid=missing,label="same"});else g.dimension_references["size0"]=new CollisionReference{pid=missing,label="same"};service.ResolveCollision(g);}}catch(InvalidOperationException){rejected=true;}Check(rejected,operation+" missing persistent CAD ID cannot rebind by label");}
 f.model.Verify(x=>x.FirstFeature(),Times.Never());Check(true,"CAD persistent resolution performs no name fallback scans");
 int valid=0;extension.Setup(x=>x.GetObjectByPersistReference3(It.IsAny<object>(),out valid)).Returns(same.Object);var transform=new Mock<MathTransform>();transform.SetupGet(x=>x.ArrayData).Returns(new[]{1.0,0,0,0,1.0,0,0,0,1.0,0,0,0,1.0,0,0,0});extension.Setup(x=>x.GetCoordinateSystemTransformByName("same")).Returns(transform.Object);service.Project.attachments.Add(new Attachment{name="exported_site",link="a",link_id=linkId,type="frame",source_name="same",source_pid=missing});var data=service.Export("robot.urdf");var items=(List<Dictionary<string,object>>)data["attachments"];Check((string)items[0]["link_id"]==linkId,"exported sidecar preserves authoritative attachment link ID");}
 static void Components(Fixture f){var extension=new Mock<ModelDocExtension>();int error=1;extension.Setup(x=>x.GetObjectByPersistReference3(It.IsAny<object>(),out error)).Returns((object)null);f.model.SetupGet(x=>x.Extension).Returns(extension.Object);f.a.Link.SWComponentPIDs.Add(new byte[]{1,2,3});var method=typeof(ProjectExport).Assembly.GetType("SWSimTool.Simulation.ProjectSourceBuilder").GetMethod("LoadComponents",BindingFlags.Static|BindingFlags.NonPublic);bool rejected=false;try{method.Invoke(null,new object[]{f.model.Object,f.tree});}catch(TargetInvocationException e){rejected=e.InnerException is InvalidDataException&&e.InnerException.Message.Contains("a");}Check(rejected,"production rejects missing CAD component instead of silently dropping its geometry");}
 static void Configurations(){var document=new SimulationStorage.Document();document.configurations["arm"]=new SimulationStorage.Entry{simulation=Project()};SimulationStorage.RemapConfigurations(document,new Dictionary<string,string>{{"A","arm"}});Check(document.configurations["arm"].configuration_id=="A","legacy CAD configuration uniquely migrates to identity");document=SimulationStorage.Parse(ExportFingerprint.Serializer().Serialize(document));SimulationStorage.RemapConfigurations(document,new Dictionary<string,string>{{"A","left_arm"}});Check(document.configurations.ContainsKey("left_arm")&&document.configurations["left_arm"].configuration_id=="A","CAD configuration rename/save/reopen retains A");SimulationStorage.RemapConfigurations(document,new Dictionary<string,string>());Check(!document.configurations.ContainsKey("left_arm")&&document.configurations.Values.Single().configuration_id=="A","CAD configuration delete leaves unresolved A");document=SimulationStorage.Parse(ExportFingerprint.Serializer().Serialize(document));SimulationStorage.RemapConfigurations(document,new Dictionary<string,string>{{"B","left_arm"}});Check(!document.configurations.ContainsKey("left_arm"),"CAD configuration same-name B never receives A");var cold=SimulationStorage.Parse(ExportFingerprint.Serializer().Serialize(document));SimulationStorage.RemapConfigurations(cold,new Dictionary<string,string>{{"B","left_arm"}});Check(!cold.configurations.ContainsKey("left_arm")&&cold.configurations.Values.Single().configuration_id=="A","CAD configuration cold persistence keeps unresolved A");var legacy=new SimulationStorage.Document();legacy.configurations["missing"]=new SimulationStorage.Entry();SimulationStorage.RemapConfigurations(legacy,new Dictionary<string,string>());string missing=legacy.configurations.Values.Single().configuration_id;SimulationStorage.RemapConfigurations(legacy,new Dictionary<string,string>{{"C","missing"}});Check(!legacy.configurations.ContainsKey("missing")&&legacy.configurations.Values.Single().configuration_id==missing,"missing legacy configuration never retries name migration");}
 static void Typed(Fixture f){var core=f.Core();string joint=core.Joints[0].Name;bool rejected=false;try{new RobotModel(core,new SimulationConfigSnapshot(Actuators:new[]{new ActuatorSnapshot("motor","motor",joint,"deleted","motor",1,1,-1,1,-1,1)}));}catch(InvalidDataException e){rejected=e.Message.Contains("deleted");}Check(rejected,"RobotModel construction rejects dangling ID even with a valid display name");}
 public static void Run(string folder){var previous=System.Environment.GetEnvironmentVariable("SWSIMTOOL_CACHE");System.Environment.SetEnvironmentVariable("SWSIMTOOL_CACHE",Path.Combine(folder,"cache"));try{var cases=Cases();foreach(var c in cases)RunCase(c,folder);Modes(folder);Mimic(folder);Legacy(folder);LegacyReadCache(folder);Configurations();Components(new Fixture(Path.Combine(folder,"components")));Typed(new Fixture(Path.Combine(folder,"typed")));Sidecar(new Fixture(Path.Combine(folder,"sidecar")));CadPid(new Fixture(Path.Combine(folder,"cad_pid")));File.WriteAllText(Path.Combine(folder,"report.json"),ExportFingerprint.Serializer().Serialize(new{status="passed",checks,cases=cases.Select(c=>new{c.name,c.kind,c.key}).ToArray()}));Console.WriteLine("Stable reference audit checks: "+checks);}finally{System.Environment.SetEnvironmentVariable("SWSIMTOOL_CACHE",previous);}}
}
'@
[StableReferenceAudit]::Run($folder)
$folder | Set-Content -LiteralPath (Join-Path $root 'build\stable-reference-audit-directory.txt')
