<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>TestRunner</AssemblyName>
    <OutputType>Exe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="SolidWorks.Interop.sldworks">
      <HintPath>$(SolidWorksDir)\SolidWorks.Interop.sldworks.dll</HintPath>
    </Reference>
    <Reference Include="SolidWorks.Interop.swconst">
      <HintPath>$(SolidWorksDir)\SolidWorks.Interop.swconst.dll</HintPath>
    </Reference>
    <Reference Include="SolidWorks.Interop.swpublished">
      <HintPath>$(SolidWorksDir)\SolidWorks.Interop.swpublished.dll</HintPath>
    </Reference>
    <Reference Include="SolidWorksTools">
      <HintPath>$(SolidWorksDir)\solidworkstools.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.runner.utility" Version="2.4.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
  </ItemGroup>
</Project>
