<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="../../../Directory.Build.props" />
  <PropertyGroup>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <ApplicationIcon />
    <OutputType>Exe</OutputType>
    <OutputPath>../../../build/upstream-tests/runner/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <BaseIntermediateOutputPath>../../../build/upstream-runner-obj/</BaseIntermediateOutputPath>
    <StartupObject />
    <SolidWorksDir Condition=" '$(SolidWorksDir)' == '' ">C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS</SolidWorksDir>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <AssemblyName>TestRunner</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="xunit.runner.utility.net452">
      <HintPath>../../../build\packages/xunit.runner.utility.2.4.1/lib/net452/xunit.runner.utility.net452.dll</HintPath>
    </Reference>
    <Reference Include="xunit.abstractions">
      <HintPath>../../../build\packages/xunit.abstractions.2.0.3/lib/net35/xunit.abstractions.dll</HintPath>
    </Reference>
    <Reference Include="SolidWorks.Interop.sldworks">
      <HintPath>$(SolidWorksDir)\SolidWorks.Interop.sldworks.dll</HintPath>
    </Reference>
    <Reference Include="SolidWorks.Interop.swconst">
      <HintPath>$(SolidWorksDir)\SolidWorks.Interop.swconst.dll</HintPath>
    </Reference>
    <Reference Include="SolidWorks.Interop.swpublished">
      <HintPath>$(SolidWorksDir)\SolidWorks.Interop.swpublished.dll</HintPath>
    </Reference>
    <Reference Include="SolidWorksTools">
      <HintPath>$(SolidWorksDir)\solidworkstools.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Windows.Forms" />
    <Compile Include="GlobalSuppressions.cs" />
    <Compile Include="TestRunner.cs" />
  </ItemGroup>
  <Import Project="../../../Directory.Build.targets" />
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>